<a href="https://colab.research.google.com/github/jokrumsvik/hands-on-python-3084712/blob/main/Copy_of_Exercises_LINEAR_ALGEBRA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Problem 1: Create Three Different Arrays with Integer Values


# Create array1 with integer values 1, 2, 3
array1 = np.array([1, 2, 3])

# Create array2 with integer values 4, 5, 6
array2 = np.array([4,5,6])

# Create array3 with integer values 7, 8, 9
array3 = np.array([7,8,9])

In [6]:
array3

array([7, 8, 9])

In [10]:
# Problem 2: Create Two Different Matrices


# Create matrix1
matrix1 = np.array([[1, 2], [3,4]])

# Create matrix2
matrix2 = np.array([[5, 6], [7,8]])

matrix2

array([[5, 6],
       [7, 8]])

In [15]:
# Problem 3: Add Matrices


result_addition =matrix1 + matrix2
result_addition

array([[ 6,  8],
       [10, 12]])

In [21]:
# Problem 4: Add and Subtract Vectors with Integer Values

# Create vector1 with integer values
vector1 = np.array([1, 2, 3])

# Create vector2 with integer values
vector2 = np.array([4, 5, 6])

# Perform vector addition
result_addition =vector1 + vector2
result_addition

# Perform vector subtraction
result_subtraction= vector1 - vector2
result_subtraction

array([-3, -3, -3])

In [22]:
# Problem 5: Multiply Array by Scalar

# Scalar value
scalar = 5

# Array

array_to_multiply = array1

# Multiply the array by the scalar

result_scalar_multiplication = scalar*array1
result_scalar_multiplication

array([ 5, 10, 15])

In [25]:
# Problem 6: Multiply Matrix by Scalar

# Create a 2x2 matrix with integer values
matrix = np.array([[5,6],[7,8]])

# Scalar value for multiplication
scalar = 41

# Multiply the matrix by the scalar
result_scalar_multiplication = matrix*scalar
result_scalar_multiplication

array([[205, 246],
       [287, 328]])

In [ ]:
# Problem 7: Find Determinant of  Matrix 2

# Create matrix1
matrix1 = np.array([[1, 2], [3, 4]])

# Calculate the determinant
determinant_matrix1 = np.linalg.det(matrix1)



matrix2 =

determinant_matrix2 =

In [28]:
# Problem 8: Find Rank of 3x3 Matrix

# Create matrix3
matrix3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the rank
rank_matrix3 = np.linalg.matrix_rank(matrix3)
matrix3
rank_matrix3

2

In [35]:
# Create matrix3
matrix3 = np.array([[690], [50], [91], [42]])

# Calculate the rank
rank_matrix3 = np.linalg.matrix_rank(matrix3)
rank_matrix3

1

In [37]:
#Example
A = np.array([
        [2, -1, 1, 1],
        [1, 2, -1, -1],
        [-1, 2, 2, 2],
        [1, -1, 2, 1]
    ])
b = np.array([6, 3, 14, 8])

<function numpy.array>

In [38]:


# solution of the system of linear equations with the corresponding coefficients matrix A and free coefficients b
x = np.linalg.solve(A,b)

#find the rank of A
rank_a = np.linalg.matrix_rank(A)

In [39]:
rank_a

4

In [47]:
# Problem 9: Create the matrix and solution vector for the linear system below. Find the determinant of M, the solution and the linear system and the rank


#4x + 3y + 2z = 25
#-2x + 2y + 3z = -10
#3x -5y + 2z = -4

MinMatrix =   np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
rank_MinMatrix = np.linalg.matrix_rank(MinMatrix)
rank_MinMatrix





3